// Static viewer: one self-contained HTML page per archive (record.json inlined) and a gallery. No server, no dependencies.
import { existsSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { selectArcs, selectBreaks, selectThreads, finalReason, type Record_ } from "./archive.ts";
import { scene3dScript } from "./site3d.ts";

const esc = (s: unknown) => String(s ?? "").replace(/[&<>"']/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" }[c]!));

const CSS = `
:root{--bg:#f6f4ef;--fg:#1d1b17;--mute:#6b665c;--line:#e0dcd2;--card:#fffdf8;--acc:#b3541e;--acc2:#2f6f8f;--acc3:#5d7a3a;--acc4:#8a3e6a;--acc5:#6b665c;--warn:#c8a415}
@media(prefers-color-scheme:dark){:root:not([data-theme=light]){--bg:#16150f;--fg:#ece7da;--mute:#9a9484;--line:#2d2b23;--card:#1f1d16;--acc:#e0803c;--acc2:#6fb0d0;--acc3:#9cc26a;--acc4:#d07aa8;--acc5:#9a9484;--warn:#e2c04a}}
:root[data-theme=dark]{--bg:#16150f;--fg:#ece7da;--mute:#9a9484;--line:#2d2b23;--card:#1f1d16;--acc:#e0803c;--acc2:#6fb0d0;--acc3:#9cc26a;--acc4:#d07aa8;--acc5:#9a9484;--warn:#e2c04a}
*{box-sizing:border-box}html{-webkit-text-size-adjust:100%}
body{margin:0;background:var(--bg);color:var(--fg);font:16px/1.5 Georgia,"Iowan Old Style",serif;padding:0 16px 64px}
main{max-width:980px;margin:0 auto}h1{font-size:2rem;margin:.6em 0 .2em}h2{font-size:1.25rem;margin:2em 0 .5em;border-bottom:1px solid var(--line);padding-bottom:.25em}
.mute{color:var(--mute)}.premise{font-style:italic;font-size:1.1rem}.small{font-size:.85rem}
.bars{display:grid;gap:6px;margin:12px 0}.bar{display:grid;grid-template-columns:200px 1fr 60px;gap:10px;align-items:center}.bar i{display:block;height:14px;background:var(--acc);border-radius:3px}.bar:nth-child(2) i{background:var(--acc2)}.bar:nth-child(3) i{background:var(--acc3)}.bar:nth-child(4) i{background:var(--acc4)}.bar:nth-child(5) i{background:var(--acc5)}
.card{background:var(--card);border:1px solid var(--line);border-radius:8px;padding:14px 16px;margin:12px 0}
.replay{position:relative}.sticky{position:sticky;top:0;z-index:2}.board .row{display:flex;flex-wrap:wrap;gap:8px 18px;align-items:baseline}
.phone{display:none}.mapcard{padding:8px}#map{width:100%;height:auto;display:block;border-radius:6px;background:var(--bg)}.maplegend{margin-top:6px}
@media(max-width:600px){.phone{display:inline-block}.board{font-size:.9rem}.board .bars{gap:3px}.board .bar i{height:10px}.sticky:not(.open) .board .detail{display:none}.sticky:not(.open) .board .bars{display:none}}
.controls button{font:inherit;background:var(--card);color:var(--fg);border:1px solid var(--line);border-radius:6px;padding:4px 10px;cursor:pointer}.controls button[aria-pressed=true]{background:var(--fg);color:var(--bg)}
.controls input[type=range]{width:100%}
#view3d::after{content:"";position:absolute;inset:0;pointer-events:none;background:radial-gradient(ellipse at center,rgba(0,0,0,0) 55%,rgba(30,20,10,0.35) 100%)}.cast{display:grid;grid-template-columns:repeat(auto-fill,minmax(118px,1fr));gap:8px;margin-top:10px}.pc{background:var(--card);border:1px solid var(--line);border-radius:10px;padding:8px;font-size:12px;line-height:1.25;position:relative;transition:box-shadow .2s,transform .2s;cursor:pointer}.pc.on{box-shadow:0 0 0 2px var(--warn);transform:translateY(-2px)}.pc.with{box-shadow:0 0 0 2px var(--acc2)}.pc.dead{opacity:.45}.pc .av{width:40px;height:40px;border-radius:50%;display:inline-block;vertical-align:middle;margin-right:6px}.pc b{display:block;font-size:13px}.pc .role{color:var(--mute)}.pc .bars{display:grid;gap:3px;margin:6px 0 0}.pc .bar{display:grid;grid-template-columns:34px 1fr;gap:6px;align-items:center;font-size:10px;color:var(--mute)}.pc .bar i{display:block;height:5px;border-radius:3px;background:var(--acc3)}.pc .bar i.food{background:var(--acc2)}.pc .bar i.money{background:var(--warn)}.pc .imp{position:absolute;left:6px;right:6px;bottom:-8px;display:flex;flex-wrap:wrap;gap:3px;pointer-events:none}.pc .imp span{background:#1d1b17;color:#fff;border-radius:8px;padding:1px 6px;font-size:10px;animation:pop 3.2s forwards}.pc .imp span.bad{background:#8a2f1e}.pc .imp span.good{background:#3e7a2a}@keyframes pop{0%{opacity:0;transform:translateY(6px)}12%{opacity:1;transform:none}80%{opacity:1}100%{opacity:0}}.pc .tie{margin-top:4px;font-size:10px;color:var(--mute)}.tl{display:grid;grid-template-columns:repeat(60,1fr);gap:1px;margin-top:10px;height:14px}.tl i{display:block;background:var(--line);border-radius:2px;cursor:pointer;position:relative}.tl i.ep{background:var(--warn)}.tl i.died{background:var(--acc)}.tl i.now{outline:2px solid var(--fg);outline-offset:1px}.tl i:hover::after{content:attr(data-l);position:absolute;bottom:18px;left:0;background:var(--card);border:1px solid var(--line);padding:2px 6px;border-radius:6px;white-space:nowrap;font-size:11px;z-index:2}
.watch{font-size:12px;padding:2px 8px;margin-right:6px;vertical-align:middle}.hud{position:absolute;left:12px;right:12px;top:10px;display:flex;gap:14px;align-items:center;pointer-events:none;font-size:13px;color:#f3eee2;text-shadow:0 1px 3px rgba(0,0,0,.7)}.hud #hudseason{font-weight:700;font-size:15px}.hud #hudepoch{flex:1;color:#ffd27a}.hud #hudpop{font-variant-numeric:tabular-nums;white-space:nowrap}.bigplay{position:absolute;left:50%;top:50%;transform:translate(-50%,-50%);width:84px;height:84px;border-radius:50%;border:0;background:rgba(255,253,248,0.92);color:#1d1b17;font-size:34px;cursor:pointer;box-shadow:0 6px 24px rgba(0,0,0,.4);padding-left:6px}.bigplay:hover{background:#fff}.bigplay[hidden]{display:none}details.fold{margin:14px 0}details.fold>summary{cursor:pointer;font-family:Georgia,serif;font-size:20px;font-weight:700;padding:6px 0}
.titlecard{position:absolute;left:0;right:0;top:34%;text-align:center;pointer-events:none;opacity:0;transition:opacity .5s;color:#fff;text-shadow:0 2px 10px rgba(0,0,0,.8);font-size:28px;font-family:Georgia,serif}.titlecard span{font-size:16px;color:#ffd27a;font-family:system-ui,sans-serif}.titlecard.show{opacity:1}.narr{position:absolute;left:12px;right:12px;bottom:12px;text-align:center;pointer-events:none;opacity:0;transition:opacity .3s;background:rgba(20,18,14,0.72);color:#f3eee2;border-radius:10px;padding:8px 14px;font-size:15px;backdrop-filter:blur(4px)}.narr.show{opacity:1}@media(max-width:640px){#view3d{display:flex;flex-direction:column;overflow:visible}#view3d canvas{order:0}.narr,.cap{position:static;order:10;margin-top:6px;backdrop-filter:none}.cap{padding-right:40px}.hud,.titlecard,.bigplay{order:0}}.cap{position:absolute;left:12px;right:12px;bottom:56px;background:rgba(20,18,14,0.78);color:#f3eee2;border-radius:10px;padding:10px 44px 10px 14px;font-size:15px;line-height:1.35;pointer-events:none;backdrop-filter:blur(4px)}.cap #capwho{font-weight:700;margin-bottom:2px;color:#ffd27a}.cap #captext i{color:#cfc8b8}.cap #unwatch{position:absolute;right:8px;top:8px;pointer-events:auto;font-size:12px;padding:2px 7px}
.feed{list-style:none;padding:0;margin:0}.jl li.yr{font-weight:700;border:0;padding:12px 0 2px;color:var(--fg)}.jl li.l0{color:var(--mute);border-bottom:0;padding:2px 0}.jl li.ep{border-bottom:0;padding:2px 0}.jl .sit{color:var(--mute)}.jl li.l1,.jl li.l2,.jl li.l3{padding:5px 0}.feed li{padding:6px 0;border-bottom:1px dashed var(--line)}.feed .h{color:var(--mute);font-variant-numeric:tabular-nums;margin-right:8px}.feed .l3{font-weight:700}.feed .l1{color:var(--mute);font-size:.9rem}.feed .q{color:var(--mute);font-style:italic}.feed .b{color:var(--acc2)}
table{border-collapse:collapse;width:100%;font-size:.9rem}th,td{text-align:left;padding:6px 8px;border-bottom:1px solid var(--line);vertical-align:top}th{color:var(--mute);font-weight:600}
details{margin:6px 0}summary{cursor:pointer}svg text{font:16px sans-serif;fill:var(--mute)}@media(max-width:600px){svg text{font:26px sans-serif}}
.chip{display:inline-block;padding:1px 8px;border:1px solid var(--line);border-radius:999px;font-size:.8rem;color:var(--mute);margin-right:6px}
a{color:var(--acc2)}.grid2{display:grid;gap:12px;grid-template-columns:1fr}@media(min-width:760px){.grid2{grid-template-columns:1fr 1fr}}
.gallery a.card{display:block;text-decoration:none;color:inherit}.gallery a.fork{margin-left:18px;border-left:3px solid var(--line)}.gallery .bars{margin:6px 0}.gallery .bar{grid-template-columns:120px 1fr 40px}
@media(max-width:600px){.bar{grid-template-columns:110px 1fr 44px}}
`;

function chart(r: Record_): string {
  const W = 900, H = 220, pad = { l: 36, r: 40, t: 12, b: 28 };
  const n = r.citizens.length, hours = r.hours;
  const x = (h: number) => pad.l + (h / hours) * (W - pad.l - pad.r), y = (v: number) => pad.t + (1 - v / n) * (H - pad.t - pad.b);
  const cols = ["var(--acc)", "var(--acc2)", "var(--acc3)", "var(--acc4)", "var(--acc5)"];
  const paths = r.ending.choices.map((c, i) => `<path d="${r.leanHistory.map((l, k) => `${k ? "L" : "M"}${x(l.hour).toFixed(1)},${y(l.tally[c.id] ?? 0).toFixed(1)}`).join(" ")}" fill="none" stroke="${cols[i % 4]}" stroke-width="2.5"/>`).join("");
  const und = `<path d="${r.leanHistory.map((l, k) => `${k ? "L" : "M"}${x(l.hour).toFixed(1)},${y(l.tally.undecided ?? 0).toFixed(1)}`).join(" ")}" fill="none" stroke="var(--mute)" stroke-width="1.5" stroke-dasharray="4 3"/>`;
  const phases = r.phases.map((p, i) => { const end = r.phases[i + 1]?.hour ?? hours; return `<rect x="${x(p.hour)}" y="${pad.t}" width="${x(end) - x(p.hour)}" height="${H - pad.t - pad.b}" fill="${i % 2 ? "var(--line)" : "none"}" opacity=".35"/><text x="${x(p.hour) + 4}" y="${pad.t + 14}"${i === r.phases.length - 1 ? ` text-anchor="end" x="${W - pad.r - 4}"` : ""}>${esc(p.name)}</text>`; }).join("");
  const events = r.events.filter((e) => e.fired).map((e) => `<line x1="${x(e.at)}" x2="${x(e.at)}" y1="${pad.t}" y2="${H - pad.b}" stroke="var(--warn)" stroke-width="${e.stakes}" opacity=".7"><title>h${e.at}: ${esc(e.headline)}</title></line>`).join("");
  const axis = `<line x1="${pad.l}" x2="${W - pad.r}" y1="${H - pad.b}" y2="${H - pad.b}" stroke="var(--line)"/>${[0, 12, 24, 36, 48, 60, 72].filter((h) => h <= hours).map((h) => `<text x="${x(h)}" y="${H - 8}" text-anchor="${h === hours ? "end" : "middle"}">h${h}</text>`).join("")}<text x="4" y="${y(n) + 4}">${n}</text><text x="4" y="${y(0)}">0</text>`;
  const legend = r.ending.choices.map((c, i) => `<span class="chip" style="border-color:${cols[i % 4]}">${esc(c.label)}</span>`).join("") + `<span class="chip">undecided (dashed)</span><span class="chip" style="border-color:var(--warn)">events</span>`;
  return `<div class="card"><div class="small mute">How the room moved — citizens leaning each way, hour by hour</div><svg viewBox="0 0 ${W} ${H}" width="100%" role="img" aria-label="tally over time">${phases}${events}${paths}${und}${axis}</svg><div>${legend}</div></div>`;
}

export function renderWorldPage(r: Record_, extras: { forkMd?: string } = {}): string {
  const chron = (r as any).mode === "chronicle" ? (r as any) : null;
  const total = Object.values(r.outcome).reduce((a, b) => a + b, 0);
  const lbl = (id: string | null) => id ? r.ending.choices.find((c) => c.id === id)?.label ?? id : "undecided";
  const bars = r.ending.choices.map((c) => `<div class="bar"><span>${esc(c.label)}</span><span><i style="width:${Math.round(((r.outcome[c.id] ?? 0) / total) * 100)}%"></i></span><span>${r.outcome[c.id] ?? 0} · ${Math.round(((r.outcome[c.id] ?? 0) / total) * 100)}%</span></div>`).join("");
  const fin = r.editions[r.editions.length - 1];
  const arcs = selectArcs(r).map((c) => { const commit = c.diary.find((d) => d.text.startsWith("decided:")); return `<li><b>${esc(c.name)}</b>, ${esc(c.role)}: ${c.leanTimeline.map((l, i) => i === 0 ? `started ${esc(lbl(l.lean))}` : `h${l.hour} → ${esc(lbl(l.lean))}${l.because ? ` <span class="mute">(${esc(l.because)})</span>` : ""}`).join("; ")}${commit ? `; committed h${commit.hour}${commit.because ? ` <span class="mute">— ${esc(commit.because)}</span>` : ""}` : "; never committed"}. Ended <b>${esc(lbl(c.finalChoice))}</b>.</li>`; }).join("");
  const breaks = selectBreaks(r).map((t) => `<li><b>${esc(t.aName)} ↔ ${esc(t.bName)}</b>: ${t.startWord} → ${t.endWord} — ${esc(t.why)}</li>`).join("");
  const threads = selectThreads(r).map((t) => `<li><b>${esc(t.aName)} ↔ ${esc(t.bName)}</b>: ${t.startWord} → ${t.endWord} <span class="mute">— ${esc(t.why)}</span></li>`).join("");
  const watchFor = r.watchFor.map((w) => `<li>${esc(w.hint)}</li>`).join("");
  const citizens = r.citizens.map((c) => `<tr><td>${esc(c.name)}${c.named ? "" : ' <span class="chip" title="generated to fill the cast; not one of the scenario\'s written characters">generated</span>'}</td><td>${esc(c.role)}</td><td>${esc(lbl(c.lean0))}</td><td>${c.committedAt !== null ? `h${c.committedAt}` : c.leanedAt === null ? "never leaned" : "never"}</td><td><b>${esc(lbl(c.finalChoice))}</b></td><td class="small mute">${esc(finalReason(c) ?? "")}</td><td>${c.topTie ? `${esc(c.topTie.name)}` : "—"}</td></tr>`).join("");
  // the complete chronological record, grouped by phase — the same lines record.md has, so nothing depends on scrubbing
  const rollup = new Map<number, string[]>();
  for (const b of r.beats.filter((b) => b.level === 1 && / now leans /.test(b.headline))) { const m = /^(.+?) \((.+?)\) now leans (.+)$/.exec(b.headline); if (m) (rollup.get(b.hour) ?? rollup.set(b.hour, []).get(b.hour)!).push(`${m[1]} (${m[3]})`); }
  const lines = [...r.beats.filter((b) => b.level >= 2).map((b) => ({ hour: b.hour, sort: 1, html: `<li class="l${b.level}"><span class="h">h${String(b.hour).padStart(2, "0")}</span>${b.level === 3 ? "••• " : "•• "}${esc(b.headline)}${b.because ? ` <span class="b">— because ${esc(b.because)}</span>` : ""}${b.thought ? ` <span class="q">— “${esc(b.thought)}”</span>` : ""}</li>` })),
    ...[...rollup.entries()].map(([hour, who]) => ({ hour, sort: 0, html: `<li class="l1"><span class="h">h${String(hour).padStart(2, "0")}</span>· ${who.length} make up their minds: ${esc(who.join(", "))}</li>` }))].sort((a, b) => a.hour - b.hour || a.sort - b.sort);
  const byPhase = r.phases.map((p, i) => { const end = r.phases[i + 1]?.hour ?? r.hours + 1; return { p, items: lines.filter((l) => l.hour >= p.hour && l.hour < end) }; }).filter((x) => x.items.length);
  const record = byPhase.map(({ p, items }) => `<details open><summary><b>${esc(p.name)}</b> <span class="mute">from hour ${p.hour} · ${items.length} moments</span></summary><ol class="feed">${items.map((l) => l.html).join("")}</ol></details>`).join("");
  const diaries = r.citizens.map((c) => `<details><summary><b>${esc(c.name)}</b>, ${c.age}, ${esc(c.role)} — started ${esc(lbl(c.lean0))}, ended <b>${esc(lbl(c.finalChoice))}</b></summary><p class="small mute">Wants ${esc(c.want)}. Fears ${esc(c.fear)}.${c.topTie ? ` Closest to ${esc(c.topTie.name)} — ${esc(c.topTie.why)}.` : ""}</p><ul class="small">${c.diary.map((d) => `<li><span class="h">h${d.hour}</span> ${esc(d.text)}${d.because ? ` <span class="b">— because ${esc(d.because)}</span>` : ""}${d.said ? ` <span class="q">— ${esc(d.said)}</span>` : ""}</li>`).join("")}</ul></details>`).join("");
  const events = r.events.map((e) => `<tr><td>${esc(e.headline)}</td><td>h${e.at}</td><td>${e.skipped ? "skipped (seed)" : "yes"}</td><td>${e.fired ? e.reached : "—"}</td></tr>`).join("");
  const editions = r.editions.map((e) => `<div class="card"><div class="mute small">Hour ${e.hour}</div>${e.headlines.map((h) => `<div><b>${esc(h)}</b></div>`).join("")}<p>${esc(e.body)}</p>${e.quote ? `<blockquote>“${esc(e.quote.text)}” — ${esc(e.quote.who)}</blockquote>` : ""}</div>`).join("");
  // chronicle-only blocks
  const linkNames = (t: string) => chron ? chron.citizens.reduce((acc: string, c: any) => acc.split(esc(c.name)).join(`<a href="#j-${esc(c.id)}" data-watchlink="${esc(c.id)}">${esc(c.name)}</a>`), t) : t;
  const verdicts = chron ? `<div class="card"><h2 style="margin-top:0">Verdicts</h2><ul>${chron.verdicts.map((v: any) => `<li><b>${esc(v.title)}.</b> ${linkNames(esc(v.text))}</li>`).join("")}</ul></div>` : "";
  const popChart = chron ? (() => { const W = 900, H = 200, pad = { l: 36, r: 40, t: 12, b: 28 }; const n = chron.citizens.length, T = chron.hours; const x = (k: number) => pad.l + (k / T) * (W - pad.l - pad.r), y = (v: number) => pad.t + (1 - v / n) * (H - pad.t - pad.b); const line = (key: string, col: string) => `<path d="${chron.population.map((p: any, i: number) => `${i ? "L" : "M"}${x(p.tick).toFixed(1)},${y(p[key]).toFixed(1)}`).join(" ")}" fill="none" stroke="${col}" stroke-width="2.5"/>`; const ep = chron.events.map((e: any) => `<rect x="${x(e.at)}" y="${pad.t}" width="${Math.max(2, x(e.at + (e.fxHours ?? 1)) - x(e.at))}" height="${H - pad.t - pad.b}" fill="var(--warn)" opacity=".18"><title>${esc(e.headline)}</title></rect><text x="${x(e.at) + 3}" y="${pad.t + 12}">${esc(e.id)}</text>`).join(""); const years = Array.from({ length: Math.floor(T / 4) + 1 }, (_, i) => i * 4).map((k) => `<text x="${x(k)}" y="${H - 8}" text-anchor="middle">${k ? `y${k / 4}` : ""}</text>`).join(""); return `<div class="card"><div class="small mute">The years — alive, dead, gone, and who was sick, starving or without a roof</div><svg viewBox="0 0 ${W} ${H}" width="100%" role="img" aria-label="population over time">${ep}${line("alive", "var(--acc3)")}${line("dead", "var(--acc)")}${line("left", "var(--mute)")}${line("starving", "var(--acc2)")}${line("homeless", "var(--acc4)")}<text x="4" y="${y(n) + 4}">${n}</text><text x="4" y="${y(0)}">0</text>${years}</svg><div><span class="chip" style="border-color:var(--acc3)">alive</span><span class="chip" style="border-color:var(--acc)">dead</span><span class="chip">gone</span><span class="chip" style="border-color:var(--acc2)">starving</span><span class="chip" style="border-color:var(--acc4)">homeless</span><span class="chip" style="border-color:var(--warn)">epochs</span></div></div>`; })() : "";
  const jline = (j: any) => j.kind === "epoch" ? `<li data-t="${j.tick}" class="l1 ep"><span class="h">${esc(j.label.split(", ")[1])}</span><i>${esc(j.outcome)}</i></li>` : j.kind === "life" ? `<li data-t="${j.tick}" class="l${j.death ? 3 : j.quiet ? 0 : 2}"><span class="h">${esc(j.label.split(", ")[1])}</span>${esc(j.outcome)}</li>` : j.quiet ? `<li data-t="${j.tick}" class="l0"><span class="h">${esc(j.label.split(", ")[1])}</span>${esc(j.outcome)}${j.thought ? ` <span class="q">“${esc(j.thought)}”</span>` : ""}</li>` : `<li data-t="${j.tick}" class="l${j.deed && (j.deed.harm >= 0.5 || j.deed.help >= 0.5) ? 3 : j.deed ? 2 : 1}"><span class="h">${esc(j.label.split(", ")[1])}</span><i class="sit">${esc(j.situation)}</i> <b>${esc(j.option)}</b> <span class="mute">— ${esc(j.outcome)}</span>${j.deed ? ` <span class="chip" style="border-color:${j.deed.harm >= 0.3 ? "var(--acc)" : "var(--acc3)"}">${esc(j.deed.kind)}</span>` : ""}${j.thought ? ` <span class="q">— “${esc(j.thought)}”</span>` : ""}</li>`;
  const byYear = (js: any[]) => { const out: string[] = []; let y = ""; for (const j of js) { const yy = j.label.split(", ")[0]; if (yy !== y) { y = yy; out.push(`<li class="yr">${esc(yy)}</li>`); } out.push(jline(j)); } return out.join(""); };
  const journeys = chron ? chron.citizens.slice().sort((a: any, b: any) => Number(b.named) - Number(a.named) || b.harm + b.help - a.harm - a.help).map((c: any) => `<details id="j-${esc(c.id)}"><summary><button class="watch" data-watch="${esc(c.id)}" title="replay their life in the world">▶ watch</button> <b>${esc(c.name)}</b>, ${esc(c.role)} — ${c.alive && !c.left ? `alive, ${esc(c.status)}` : c.left ? "left" : `died of ${esc(c.cause)}, ${esc(chron.tickLabels[c.diedAt - 1])}`} <span class="chip" style="border-color:var(--acc)">harm ${c.harm.toFixed(1)}</span><span class="chip" style="border-color:var(--acc3)">help ${c.help.toFixed(1)}</span>${c.children === 1 ? `<span class="chip">1 child</span>` : c.children ? `<span class="chip">${c.children} children</span>` : ""}</summary><p class="small mute">Wanted ${esc(c.want)}. Feared ${esc(c.fear)}.</p><ol class="feed jl small">${byYear(c.journey)}</ol></details>`).join("") : "";
  const ledger = chron ? `<div class="grid2"><div class="card"><h2 style="margin-top:0">The ledger — worst first</h2><ul class="small">${[...chron.deeds].sort((a: any, b: any) => b.harm - a.harm).slice(0, 10).map((d: any) => `<li>${esc(chron.tickLabels[d.tick - 1])}: <b>${esc(chron.citizens.find((c: any) => c.id === d.actor).name)}</b> ${esc(d.text)}${d.witnessed ? "" : ' <span class="mute">(nobody saw)</span>'}</li>`).join("")}</ul></div><div class="card"><h2 style="margin-top:0">…and the kindest</h2><ul class="small">${[...chron.deeds].sort((a: any, b: any) => b.help - a.help).slice(0, 10).map((d: any) => `<li>${esc(chron.tickLabels[d.tick - 1])}: <b>${esc(chron.citizens.find((c: any) => c.id === d.actor).name)}</b> ${esc(d.text)}</li>`).join("")}</ul></div></div>` : "";
  const people = chron ? `<div style="overflow:auto"><table><tr><th>name</th><th>role</th><th>age</th><th>end</th><th>harm</th><th>help</th><th>children</th></tr>${[...chron.citizens].sort((a: any, b: any) => b.harm - a.harm).map((c: any) => `<tr><td>${esc(c.name)}${c.named ? "" : ' <span class="chip">generated</span>'}</td><td>${esc(c.role)}</td><td>${c.age}</td><td>${c.alive && !c.left ? esc(c.status) : c.left ? "gone" : `died of ${esc(c.cause)}, ${esc(chron.tickLabels[c.diedAt - 1])}`}</td><td>${c.harm.toFixed(1)}</td><td>${c.help.toFixed(1)}</td><td>${c.children}</td></tr>`).join("")}</table></div>` : "";
  const parent = r.parent ? `<p class="card">Forked from <a href="../${esc(r.parent.runId)}/index.html">${esc(r.parent.runId)}</a>: ${esc(r.parent.change)}. ${r.parent.firstDivergence === null ? "The timelines never part." : `Timelines part at hour ${r.parent.firstDivergence}.`}${extras.forkMd ? ` <a href="fork.md">fork.md</a>` : ""}</p>` : "";
  const data = JSON.stringify({ runId: r.runId, premise: r.premise, mode: (r as any).mode ?? "choice", tickLabels: (r as any).tickLabels ?? null, hours: r.hours, choices: r.ending.choices, prompt: r.ending.prompt, leanHistory: r.leanHistory, beats: r.beats, phases: r.phases, citizens: r.citizens.map((c) => ({ id: c.id, name: c.name, role: c.role, committedAt: c.committedAt, leanTimeline: c.leanTimeline, named: c.named, routine: c.routine ?? [], traits: (c as any).traits ?? null, partner: (c as any).partner ?? null, ties: (c as any).ties ?? null, want: (c as any).want ?? null, fear: (c as any).fear ?? null, age: (c as any).age ?? null })), threads: r.threads.map((t) => ({ a: t.a, b: t.b, aName: t.aName, bName: t.bName, startWord: t.startWord, why: t.why })), events: r.events, total, frames: r.frames ?? [], map: r.map ?? { locations: [], paths: [] }, home: Object.fromEntries(r.scenario.citizens.map((c) => [c.id, c.home])), acts: (r as any).acts ?? null, homes: chron ? Object.fromEntries(chron.citizens.map((c: any) => [c.id, c.home ?? null])) : null }).replace(/<\//g, "<\\/").replace(/<!--/g, "<\\!--");
  const summaryBlock = `<h2>${esc(r.ending.prompt)}</h2><div class="bars">${bars}</div>
${fin && !chron ? `<div class="card"><div class="mute small">Final edition</div>${fin.headlines.map((h) => `<div><b>${esc(h)}</b></div>`).join("")}<p>${esc(fin.body)}</p>${fin.quote ? `<blockquote>“${esc(fin.quote.text)}” — ${esc(fin.quote.who)}</blockquote>` : ""}</div>` : ""}
${chron ? "" : chart(r)}
${chron ? verdicts + popChart : `<div class="grid2">${arcs ? `<div class="card"><h2 style="margin-top:0">Arcs</h2><ul>${arcs}</ul></div>` : ""}${breaks ? `<div class="card"><h2 style="margin-top:0">Breaks</h2><ul>${breaks}</ul></div>` : ""}</div>
${watchFor ? `<div class="card"><h2 style="margin-top:0">Close, and chose differently</h2><ul>${watchFor}</ul></div>` : ""}`}
`;
  const replayHead = `<h2>Replay</h2>
<section class="replay">
<div class="card sticky"><div class="controls"><button id="play" aria-pressed="false">▶ Play</button> <span class="small mute">${chron ? "s/season" : "s/hour"}</span> <button data-sph="0.5">0.5</button><button data-sph="2"${chron ? "" : ' aria-pressed="true"'}>2</button><button data-sph="10">10</button>${chron ? `<button data-sph="20"${total > 14 ? ' aria-pressed="true"' : ""}>20</button><button data-sph="30"${total <= 14 ? ' aria-pressed="true"' : ""}>30</button>` : ""}<button data-sph="${chron ? 60 : 45}">${chron ? "60" : "45"}</button> <label class="small" style="white-space:nowrap"><input type="checkbox" id="minor"> routine</label> <button id="expand" class="phone" aria-pressed="false">board ▾</button><input type="range" id="scrub" min="0" max="${r.hours}" value="0" aria-label="${chron ? "season" : "hour"}"><div class="small mute" id="resume"></div></div><div class="board" id="board"></div></div>
<div class="card mapcard"><div class="controls small" style="margin-bottom:6px"><button id="mode3d" aria-pressed="true">3D world</button><button id="mode2d" aria-pressed="false">2D map</button> <label class="small" style="white-space:nowrap"><input type="checkbox" id="follow" checked> follow the action</label> <span class="mute" id="v3status">loading three.js…</span> <span id="fxlabel" style="color:var(--warn)"></span></div><div id="view3d" style="width:100%;border-radius:6px;overflow:hidden;position:relative"><div class="hud"><span id="hudseason"></span><span id="hudepoch"></span><span id="hudpop"></span></div><div id="v3title" class="titlecard"></div><button id="bigplay" class="bigplay" title="play">▶</button><div id="v3narr" class="narr"></div><div id="v3cap" class="cap" hidden><button id="unwatch" title="stop following">✕</button><div id="capwho"></div><div id="captext"></div></div></div><canvas id="map" style="display:none" aria-label="top-down map of the world: places, paths, and where every citizen is this hour"></canvas><div class="small mute maplegend" id="maplegend"></div></div>${chron ? `<div class="cast" id="cast"></div><div class="tl" id="tl" aria-label="timeline"></div>` : ""}
`;
  const feedBlock = `<p class="small mute">Newest first. The feed shows the moments up to the ${chron ? "season" : "hour"} on the scrubber.</p>
<ol class="feed" id="feed"></ol>
</section>
`;
  // a chronicle leads with the world; the reading comes after
  const chronHead = (() => { const parts = replayHead.replace("<h2>Replay</h2>\n", "").split("\n").filter(Boolean); const open = parts[0], ctl = parts[1].replace('class="card sticky"', 'class="card"'), map = parts[2]; return [open, map, ctl].join("\n") + "\n"; })();
  const fold = (title: string, inner: string, open = false) => `<details class="fold"${open ? " open" : ""}><summary>${title}</summary>${inner}</details>`;
  const body = chron ? chronHead + "</section>\n" + fold("After fifteen years — verdicts", `<p class="small mute">After ${chron.scenario.years} years: ${r.ending.choices.map((c) => `${(r.outcome[c.id] ?? 0)} ${c.label.toLowerCase()}`).join(" · ")}.</p>` + (verdicts + popChart).replace('<h2 style="margin-top:0">Verdicts</h2>', ""), false) + fold("Journeys — open a person, press ▶ watch", `<p class="small mute">Named people first, then the most eventful lives.</p>${journeys}`) + fold("The feed", `<section class="replay">${feedBlock}</section>`) + fold("The ledger and the people", ledger + people + `<h3>What happened</h3><table><tr><th>epoch</th><th>when</th><th>alive then</th></tr>${chron.events.map((e: any) => `<tr><td>${esc(e.headline)}</td><td>${esc(chron.tickLabels[e.at - 1])}</td><td>${e.reached}</td></tr>`).join("")}</table><p class="small mute">Files: <a href="record.md">record.md</a> · <a href="journeys.md">journeys.md</a> · <a href="record.json">record.json</a></p>`) : summaryBlock + replayHead + feedBlock;
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(r.title)} · seed ${r.seed}</title><style>${CSS}</style></head><body><main>
<p class="small"><a href="../index.html">← all worlds</a></p>
<h1>${esc(r.title)} <span class="mute">— seed ${r.seed}</span></h1>
${chron ? `<p class="premise">${esc(r.premise)} <span class="mute">${total} people, ${chron.scenario.years} years. Every season each of them faces a situation and chooses; dice decide what comes of it.</span></p>` : `<p class="premise">${esc(r.premise)}</p>`}
<p class="small mute"${chron ? ' style="display:none"' : ""}>Run <code>${esc(r.runId)}</code> · ${total} citizens · ${chron ? `${chron.scenario.years} years · ${r.hours} seasons` : `${r.hours} hours`} · brain: ${esc(r.brain)} · fallback rate ${(r.stats.fallbackRate * 100).toFixed(1)} %</p>
${parent}
${body}${chron ? `` : `<h2>The record</h2><p class="small mute">Every notable moment, in order. Turning points are bold. Routine hours are in <a href="record.json">record.json</a>.</p>${record}
<h2>Threads</h2><ul>${threads}</ul>
<h2>Citizens</h2><div style="overflow:auto"><table><tr><th>name</th><th>role</th><th>hour 0</th><th>committed</th><th>final</th><th>why</th><th>closest to</th></tr>${citizens}</table></div>
<h2>Editions</h2>${editions}
<h2>Diaries (unsealed)</h2>${diaries}
<h2>Events</h2><table><tr><th>event</th><th>planned</th><th>fired</th><th>reached</th></tr>${events}</table>`}
${chron ? "" : `<p class="small mute">Stats: ${r.stats.decisions} decisions · ${r.stats.firstLeans} made up their minds · ${r.stats.leanFlips} changed them · ${r.stats.wavers} wavers · ${r.stats.commits} commits · ${r.beats.filter((b) => b.level >= 2).length} beats. Files: <a href="record.md">record.md</a> · <a href="diaries.md">diaries.md</a> · <a href="record.json">record.json</a></p>`}
</main>
<script>
const D=${data};
const E=s=>String(s==null?"":s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const $=s=>document.querySelector(s);const board=$("#board"),feed=$("#feed"),scrub=$("#scrub"),play=$("#play"),minor=$("#minor");
let hour=0,sph=D.mode==="chronicle"?(D.citizens.length<=14?30:20):2,timer=null,shownIdx=0;const lbl=id=>id?(D.choices.find(c=>c.id===id)||{}).label||id:"undecided";
const short=n=>{const p=n.split(" ");return p[0].endsWith(".")&&p[1]?p[0]+" "+p[1]:p[0]};
function leanAt(c,h){let l=c.leanTimeline[0]?c.leanTimeline[0].lean:null;for(const x of c.leanTimeline){if(x.hour<=h)l=x.lean}return l}
function phaseAt(h){let p=D.phases[0].name;for(const x of D.phases)if(x.hour<=h)p=x.name;return p}
function renderBoard(h){const t=(D.leanHistory.find(l=>l.hour===h)||{tally:{}}).tally;const next=D.events.filter(e=>!e.skipped&&e.at>h).sort((a,b)=>a.at-b.at)[0];
 const bars=D.choices.map((c,i)=>'<div class="bar"><span>'+E(c.label)+'</span><span><i style="width:'+Math.round(((t[c.id]||0)/D.total)*100)+'%;background:var(--acc'+(i?i+1:'')+')"></i></span><span>'+(t[c.id]||0)+'</span></div>').join("")+'<div class="bar"><span class="mute">undecided</span><span></span><span class="mute">'+(t.undecided||0)+'</span></div>';
 const W={hostile:-2,strained:-1,neutral:0,friendly:1,close:2};const recent=D.beats.filter(b=>b.hour>h-12&&b.hour<=h&&b.level>=2&&/ ↔ /.test(b.headline));const pairs=new Map();for(const b of recent){const m=/^(.+?) ↔ (.+?): (\w+) → (\w+)/.exec(b.headline);if(!m)continue;const k=[m[1],m[2]].sort().join("|");const p=pairs.get(k)||{from:m[3],mv:0};p.to=m[4];p.mv=Math.abs((W[m[4]]||0)-(W[p.from]||0))+((W[m[4]]||0)<0?0.75:0)+(b.level===3?1:0);p.why=b.because||p.why;p.hour=b.hour;pairs.set(k,p)}
 const threads=[...pairs.entries()].sort((x,y)=>y[1].mv-x[1].mv||y[1].hour-x[1].hour).slice(0,3).map(([k,v])=>{const [a,b]=k.split("|");return E(short(a))+" ↔ "+E(short(b))+' <span class="mute">'+E(v.from+" → "+v.to+(v.why?" — "+v.why:""))+'</span>'}).join("<br>");
 const soon=D.citizens.filter(c=>c.committedAt!==null&&c.committedAt>h&&c.committedAt<=h+3).map(c=>E(short(c.name))+" ("+E(c.role)+")").slice(0,3);
 const undecidedNames=D.citizens.filter(c=>!leanAt(c,h)).map(c=>E(short(c.name)));
 const committed=D.citizens.filter(c=>c.committedAt!==null&&c.committedAt<=h).length;
 const wordNow=th=>{const last=D.beats.filter(b=>b.hour<=h&&/ ↔ /.test(b.headline)&&(b.headline.startsWith(th.aName+" ↔ "+th.bName)||b.headline.startsWith(th.bName+" ↔ "+th.aName))).pop();const m=last&&/→ (\\w+)/.exec(last.headline);return m?m[1]:th.startWord};
 const opposed=[];for(const th of D.threads){if(wordNow(th)!=="close")continue;const a=D.citizens.find(c=>c.id===th.a),b=D.citizens.find(c=>c.id===th.b);if(!a||!b)continue;const la=leanAt(a,h),lb=leanAt(b,h);if(la&&lb&&la!==lb)opposed.push(E(short(a.name))+" ("+E(lbl(la))+") and "+E(short(b.name))+" ("+E(lbl(lb))+") are close and leaning apart")}
 const tw=D.beats.filter(b=>b.hour<=h&&b.hour>h-12&&b.headline.startsWith("Watch: ")).slice(-2).map(b=>E(b.headline.slice(7)));
 const und=D.mode==="chronicle"?"":((t.undecided||0)?(undecidedNames.length<=4?"undecided: "+undecidedNames.join(", "):(t.undecided)+" undecided"):"");
 const thisSeason=D.mode==="chronicle"?D.beats.filter(b=>b.hour===h&&b.level===3).slice(0,3).map(b=>E(b.headline)).join(" · "):"";
 const tallyLine=D.choices.map(c=>E(c.label)+" "+(t[c.id]||0)).join(" · ")+" · undecided "+(t.undecided||0);
 if(D.mode==="chronicle"){board.innerHTML='<div class="row"><b>'+(h?E(D.tickLabels[h-1]):"the beginning")+'</b><span class="mute">'+E(phaseAt(h))+'</span>'+'</div><div class="small mute">'+D.choices.filter(c=>t[c.id]).map(c=>E(c.label).toLowerCase()+' '+t[c.id]).join(' · ')+(thisSeason?' · '+thisSeason:'')+'</div>';return}
 board.innerHTML='<div class="row"><b>'+(D.tickLabels?(h?E(D.tickLabels[h-1]):"the beginning"):"hour "+String(h).padStart(2,"0")+"/"+D.hours)+'</b><b>'+(D.hours-h)+(D.tickLabels?' seasons left':'h left')+'</b><span class="mute">'+E(phaseAt(h))+'</span>'+(next?'<span class="mute">· next '+(D.tickLabels?'epoch '+E(D.tickLabels[next.at-1]):'event at h'+next.at)+'</span>':'')+'</div><div class="small phone">'+tallyLine+'</div><div class="detail"><b>'+E(D.prompt)+'</b></div><div class="bars">'+bars+'</div><div class="small"><span class="mute">watch</span> '+[...tw,soon.length?"about to decide: "+soon.join(", "):"",und,committed?committed+"/"+D.total+" committed":""].filter(Boolean).join(" · ")+(opposed.length?"<br>"+opposed.slice(0,2).join("<br>"):"")+'</div>'+(threads?'<div class="small detail"><span class="mute">threads</span> '+threads+'</div>':'');}
function beatLine(b){return '<li class="l'+b.level+'"><span class="h">'+(D.tickLabels?E(D.tickLabels[b.hour-1]||"").replace("Year ","Y").replace(", ",", ").slice(0,12):"h"+String(b.hour).padStart(2,"0"))+'</span>'+(b.level===3?"••• ":b.level===2?"•• ":"· ")+E(b.headline)+(b.because?' <span class="b">— because '+E(b.because)+'</span>':'')+(b.thought?' <span class="q">— “'+E(b.thought)+'”</span>':'')+'</li>'}
function renderFeed(h){const bs=D.beats.filter(b=>b.hour<=h&&(minor.checked||b.level>=2));feed.innerHTML=bs.slice(-60).reverse().map(beatLine).join("");}
function setHour(h,animated){hour=Math.max(0,Math.min(D.hours,h));window.__apHour=hour;scrub.value=hour;renderBoard(hour);renderFeed(hour);if(typeof caption==="function")caption(hour);animateTo(hour,animated?Math.min(900,sph*600):0);if(window.__ap3d)window.__ap3d.setHour(hour,animated?(D.mode==="chronicle"?sph*1000:Math.min(1500,sph*800)):0);if(hour>=D.hours)stop();}
window.__AP=D;
$("#mode3d").onclick=()=>{$("#view3d").style.display="";$("#map").style.display="none";$("#mode3d").setAttribute("aria-pressed","true");$("#mode2d").setAttribute("aria-pressed","false")};
$("#mode2d").onclick=()=>{$("#view3d").style.display="none";$("#map").style.display="";$("#mode3d").setAttribute("aria-pressed","false");$("#mode2d").setAttribute("aria-pressed","true");animateTo(hour,0)};
function stop(){if(timer){clearInterval(timer);timer=null}play.textContent="▶ Play";play.setAttribute("aria-pressed","false")}
function start(){stop();play.textContent="❚❚ Pause";play.setAttribute("aria-pressed","true");if(D.mode==="chronicle"&&hour===0){setHour(1,false)}if(D.mode==="chronicle"&&window.__ap3d&&hour>0)window.__ap3d.setHour(hour,sph*1000);timer=setInterval(()=>setHour(hour+1,true),sph*1000)}
let watching=null;const cap=$("#v3cap");
// ---------- the cast: one card per person, live vitals, the impact of every decision ----------
const COATS=["#8a3b2f","#2f5f8a","#6a7a3a","#8a6a2a","#5a3a6a","#3a6a6a","#9a5a3a","#4a4a7a","#7a4a4a","#3a5a3a","#a06a8a","#6a5a3a"];
const H32=s=>{let h=2166136261;for(const ch of String(s)){h^=ch.charCodeAt(0);h=Math.imul(h,16777619)>>>0}return h};
const ROLEI=r=>{const n=(r||"").toLowerCase();return /clerk/.test(n)?"🧾":/min|pit/.test(n)?"⛏️":/farm/.test(n)?"🌾":/shop|keeper/.test(n)?"🧺":/publican|tavern/.test(n)?"🍺":/doctor/.test(n)?"🩺":/priest/.test(n)?"✝":"👤"};
const castEl=$("#cast");
if(castEl&&D.mode==="chronicle"){castEl.innerHTML=D.citizens.map((c,i)=>'<div class="pc" id="pc-'+i+'" data-i="'+i+'"><span class="av" style="background:'+COATS[H32(c.id)%COATS.length]+'"></span><span style="display:inline-block;vertical-align:middle;max-width:calc(100% - 50px)"><b>'+E(c.name)+'</b><span class="role">'+ROLEI(c.role)+' '+E(c.role)+(c.age?', '+c.age:'')+'</span></span><div class="bars"><div class="bar">health<i class="health"></i></div><div class="bar">food<i class="food"></i></div><div class="bar">money<i class="money"></i></div></div><div class="tie"></div><div class="imp"></div></div>').join("");
 castEl.querySelectorAll(".pc").forEach(el=>el.onclick=()=>{const c=D.citizens[Number(el.dataset.i)];watching===c.id?unwatch():watch(c.id)});
 const tl=$("#tl");if(tl){tl.innerHTML=D.tickLabels.map((l,k)=>{const t=k+1;const ep=D.events.find(e=>e.at===t);const died=(D.acts&&D.acts[k]||[]).filter(a=>a.kind==="death").map(a=>D.citizens[a.c].name.split(" ")[0]);return '<i data-t="'+t+'" class="'+(ep?"ep ":"")+(died.length?"died":"")+'" data-l="'+E(l+(ep?" · "+ep.headline:"")+(died.length?" · † "+died.join(", "):""))+'"></i>'}).join("");tl.querySelectorAll("i").forEach(el=>el.onclick=()=>{stop();setHour(Number(el.dataset.t),false)})}
 const IMPL={health:"health",food:"food",money:"money",mood:"mood",tie:"closer",children:"a child",home:"home",job:"work",partner:"married",sick:"sick"};
 window.__apCast={
  season(h,fr){if(!fr)return;D.citizens.forEach((c,i)=>{const el=$("#pc-"+i);if(!el)return;const v=fr.vitals&&fr.vitals[i];const dead=fr.at[i]==null;el.classList.toggle("dead",dead);if(v){el.querySelector(".health").style.width=Math.round(v[0]*100)+"%";el.querySelector(".food").style.width=Math.round(v[1]*100)+"%";el.querySelector(".money").style.width=Math.round(Math.min(1,v[2]/1.5)*100)+"%"}});tl&&tl.querySelectorAll("i").forEach(el=>el.classList.toggle("now",Number(el.dataset.t)===h))},
  focus(ci,ti){D.citizens.forEach((c,i)=>{const el=$("#pc-"+i);if(!el)return;el.classList.toggle("on",i===ci);el.classList.toggle("with",i===ti);const tie=el.querySelector(".tie");if(i===ci&&ti!=null&&ti>=0){const a=(c.ties||{})[D.citizens[ti].id];tie.textContent=a==null?"":"with "+D.citizens[ti].name.split(" ")[0]+": "+(a>0.3?"friends":a<-0.3?"bad blood":"neighbours")}else if(i!==ci)tie.textContent=""});if(ci>=0){const el=$("#pc-"+ci);el&&el.scrollIntoView({block:"nearest",inline:"nearest"})}},
  impact(a){if(!a.impact)return;const chips=(d,who)=>{const el=$("#pc-"+who);if(!el||!d)return;const out=[];for(const [k,v] of Object.entries(d)){if(v===undefined||v===null)continue;if(typeof v==="number"){if(k==="tie"){out.push([v>0?"good":"bad",(v>0?"closer":"colder")])}else if(k==="children"){out.push(["good","a child"])}else{const s=Math.round(v*100);if(s)out.push([s>0?"good":"bad",(s>0?"+":"")+s+" "+(IMPL[k]||k)])}}else if(k==="sick")out.push([v?"bad":"good",v?"falls sick":"recovers"]);else if(k==="home")out.push([v?"good":"bad",v?"a roof":"no roof"]);else if(k==="partner")out.push(["good","married"]);else if(k==="job")out.push([v?"good":"bad",v?"work":"no work"])}
   const box=el.querySelector(".imp");box.innerHTML=out.map(([cls,t])=>'<span class="'+cls+'">'+E(t)+'</span>').join("")};
   chips(a.impact.self,a.c);if(a.target!=null)chips(a.impact.target,a.target)}
 };}
function journeyOf(id){const el=document.getElementById("j-"+id);if(!el)return {};const by={};el.querySelectorAll("li[data-t]").forEach(li=>{const k=li.dataset.t;const lab=li.querySelector(".h");(by[k]=by[k]||[]).push(li.innerHTML.replace(lab?lab.outerHTML:"","").replace(/<span class="chip[^>]*>/g,' · <span class="chip">').trim())});return by}
function caption(h){if(!watching)return;const c=D.citizens.find(c=>c.id===watching);const lines=(watching&&journeyOf(watching)[String(h)])||[];const end=(D.acts&&D.acts[h-1]||[]).find(a=>D.citizens[a.c].id===watching&&(a.kind==="death"||a.kind==="leave"));
 $("#capwho").textContent=c.name+" · "+c.role+" — "+(h?D.tickLabels[h-1]:"the beginning");$("#captext").innerHTML=lines.length?lines.map(l=>l.replace(/ \(([^)]*)\)(?=\s*(<|$))/,"")).filter(l=>/<i class="sit">|<b>/.test(l)).concat(lines.filter(l=>!/<i class="sit">|<b>/.test(l))).slice(0,2).join("<br>"):(h?"<i>nothing this season</i>":"");
 if(end){setTimeout(()=>{if(watching===c.id)stop()},Math.min(4000,sph*900))}}
function watch(id){watching=id;cap.hidden=false;$("#mode3d").click();if(window.__ap3d)window.__ap3d.watch(D.citizens.findIndex(c=>c.id===id));document.querySelectorAll("[data-watch]").forEach(b=>b.setAttribute("aria-pressed",String(b.dataset.watch===id)));$("#view3d").scrollIntoView({behavior:"smooth",block:"center"});if(sph>20){sph=20;document.querySelectorAll("[data-sph]").forEach(x=>x.setAttribute("aria-pressed",String(x.dataset.sph==="20")))}setHour(0,false);caption(0);start()}
function unwatch(){watching=null;cap.hidden=true;if(window.__ap3d)window.__ap3d.watch(-1);document.querySelectorAll("[data-watch]").forEach(b=>b.setAttribute("aria-pressed","false"))}
document.querySelectorAll("[data-watch]").forEach(b=>b.onclick=ev=>{ev.preventDefault();ev.stopPropagation();watching===b.dataset.watch?unwatch():watch(b.dataset.watch)});
$("#unwatch").onclick=unwatch;document.querySelectorAll("[data-watchlink]").forEach(a=>a.onclick=ev=>{ev.preventDefault();const el=document.getElementById("j-"+a.dataset.watchlink);if(el){el.open=true}watch(a.dataset.watchlink)});const bigplay=$("#bigplay");if(bigplay){bigplay.onclick=()=>{start();$("#view3d").scrollIntoView({behavior:"smooth",block:"start"})};const syncBig=()=>{bigplay.hidden=!!timer};new MutationObserver(syncBig).observe(play,{attributes:true});syncBig()}
play.onclick=()=>timer?stop():start();scrub.oninput=()=>{stop();setHour(Number(scrub.value))};minor.onchange=()=>renderFeed(hour);
// ---- top-down map ----
const canvas=$("#map"),ctx=canvas.getContext("2d");const COLS=["#b3541e","#2f6f8f","#5d7a3a","#8a3e6a","#6b665c"];
const MW=960,MH=540;canvas.width=MW*2;canvas.height=MH*2;ctx.scale(2,2);
const locs=D.map.locations,paths=D.map.paths;const LP={};
(function layout(){const n=locs.length;if(!n)return;const given=locs.every(l=>typeof l.x==="number");
 locs.forEach((l,i)=>{LP[l.id]=given?{x:l.x*MW,y:l.y*MH}:{x:MW/2+Math.cos(i/n*2*Math.PI-Math.PI/2)*MW*0.34,y:MH/2+Math.sin(i/n*2*Math.PI-Math.PI/2)*MH*0.36}});
 if(given)return;// relax: pull linked places together, push all apart, keep inside
 const adj=new Set(paths.map(p=>p.join("|")).concat(paths.map(p=>p[1]+"|"+p[0])));
 for(let it=0;it<300;it++){for(const a of locs)for(const b of locs){if(a===b)continue;const A=LP[a.id],B=LP[b.id];let dx=B.x-A.x,dy=B.y-A.y;const d=Math.hypot(dx,dy)||1;dx/=d;dy/=d;const linked=adj.has(a.id+"|"+b.id);const want=linked?260:360;const f=(d-want)*(linked?0.02:(d<want?0.02:0));A.x+=dx*f;A.y+=dy*f}
  for(const l of locs){const P=LP[l.id];P.x=Math.min(MW-130,Math.max(130,P.x));P.y=Math.min(MH-80,Math.max(80,P.y))}}})();
// occupants of a place sit on concentric rings, named citizens innermost, in a stable order — so a crowd reads as a crowd
function seatsFor(fr){const by={};D.citizens.forEach((c,i)=>{if(fr.at[i]==null)return;(by[fr.at[i]]=by[fr.at[i]]||[]).push(i)});const out={};for(const loc in by){const idx=by[loc].slice().sort((a,b)=>Number(D.citizens[b].named)-Number(D.citizens[a].named)||a-b);const P=LP[loc]||{x:MW/2,y:MH/2};let k=0,ring=0;while(k<idx.length){const cap=ring===0?1:ring*6;const n=Math.min(cap,idx.length-k);for(let j=0;j<n;j++,k++){const a=(j/n)*2*Math.PI+ring*0.6;out[idx[k]]={x:P.x+Math.cos(a)*ring*20,y:P.y+8+Math.sin(a)*ring*11}}ring++}}return out}
const seatCache={};function posAt(i,h){const fr=frameAt(h);if(!fr)return null;const s=seatCache[h]||(seatCache[h]=seatsFor(fr));return s[i]||null}
let anim={from:null,to:null,t0:0,dur:0};let lastHere={};
canvas.addEventListener("mousemove",(ev)=>{const R=canvas.getBoundingClientRect();const mx=(ev.clientX-R.left)/R.width*MW,my=(ev.clientY-R.top)/R.height*MH;let best=null,bd=14;for(const c of D.citizens){const P=lastHere[c.id];if(!P)continue;const d=Math.hypot(P.x-mx,P.y-my);if(d<bd){bd=d;best=c}}canvas.title=best?best.name+" — "+best.role+" · "+lbl(leanAt(best,hour))+(best.committedAt!==null&&best.committedAt<=hour?" (committed)":""):"";});
function frameAt(h){return D.frames[Math.max(0,Math.min(D.frames.length-1,h-1))]||null}
function drawMap(h,frac){ctx.clearRect(0,0,MW,MH);const dark=matchMedia("(prefers-color-scheme: dark)").matches&&document.documentElement.dataset.theme!=="light";const ink=dark?"#ece7da":"#1d1b17",mute=dark?"#9a9484":"#6b665c",plate=dark?"#26241b":"#efe9dc",line=dark?"#3a3729":"#d9d3c4";
 ctx.lineWidth=3;ctx.strokeStyle=line;for(const [a,b] of paths){const A=LP[a],B=LP[b];if(!A||!B)continue;ctx.beginPath();ctx.moveTo(A.x,A.y);ctx.lineTo(B.x,B.y);ctx.stroke()}
 const fired=D.events.filter(e=>e.fired&&e.at===h);
 for(const l of locs){const P=LP[l.id];const glow=fired.some(e=>e.where===l.id||e.where==="all");ctx.beginPath();ctx.ellipse(P.x,P.y+10,92,52,0,0,2*Math.PI);ctx.fillStyle=plate;ctx.fill();ctx.strokeStyle=glow?"#c8a415":line;ctx.lineWidth=glow?4:1.5;ctx.stroke();ctx.fillStyle=ink;ctx.font="bold 13px sans-serif";ctx.textAlign="center";ctx.fillText(l.name,P.x,P.y-50);ctx.fillStyle=mute;ctx.font="10px sans-serif";ctx.fillText(l.tags.join(" · "),P.x,P.y-37)}
 const fr=frameAt(h),prev=frameAt(h-1);if(!fr)return;
 const here={};D.citizens.forEach((c,i)=>{const to=posAt(i,h);if(!to)return;const from=(prev?posAt(i,h-1):null)||to;const x=from.x+(to.x-from.x)*frac,y=from.y+(to.y-from.y)*frac;here[c.id]={x,y};const li=fr.lean[i];const col=li?COLS[D.choices.findIndex(ch=>ch.id===li)%5]:mute;
  ctx.beginPath();ctx.arc(x,y,c.named?7:5,0,2*Math.PI);ctx.fillStyle=col;ctx.fill();if(fr.committed[i]){ctx.lineWidth=2;ctx.strokeStyle=ink;ctx.stroke()}
  if(c.named){ctx.fillStyle=ink;ctx.font="11px sans-serif";const left=i%2;ctx.textAlign=left?"right":"left";ctx.fillText(short(c.name),x+(left?-9:9),y+4)}});
 // ties that moved this hour: a brief line between the two
 for(const b of D.beats.filter(b=>b.hour===h&&/ ↔ /.test(b.headline)&&b.who&&b.who.length>1)){const A=here[b.who[0]],B=here[b.who[1]];if(!A||!B)continue;const bad=/→ (strained|hostile)/.test(b.headline);ctx.beginPath();ctx.moveTo(A.x,A.y);ctx.lineTo(B.x,B.y);ctx.strokeStyle=bad?"#b3541e":"#5d7a3a";ctx.lineWidth=2;ctx.setLineDash([4,3]);ctx.stroke();ctx.setLineDash([])}
 // what was said this hour: up to four bubbles
 ctx.font="12px Georgia,serif";const stack={};for(const ln of fr.lines.slice(0,5)){const c=D.citizens[ln.c];const loc=fr.at[ln.c];const P=LP[loc]||{x:MW/2,y:MH/2};const n=(stack[loc]=(stack[loc]||0)+1);const txt=short(c.name)+": "+(ln.kind==="say"?"":"(thinks) ")+ln.text.slice(0,56)+(ln.text.length>56?"…":"");const w=ctx.measureText(txt).width+14;const bx=Math.min(MW-w-6,Math.max(6,P.x-w/2)),by=P.y-62-n*22;ctx.fillStyle="#fffdf8";ctx.globalAlpha=0.95;ctx.beginPath();ctx.roundRect(bx,by-14,w,20,6);ctx.fill();ctx.globalAlpha=1;ctx.fillStyle="#1d1b17";ctx.textAlign="left";ctx.fillText(txt,bx+7,by)}
 lastHere=here;
 for(const e of fired){ctx.fillStyle="#c8a415";ctx.font="bold 12px sans-serif";ctx.textAlign="center";ctx.fillText("⚡ "+e.headline,MW/2,MH-14)}}
$("#maplegend").innerHTML=(D.mode==="chronicle"?"":D.choices.map((c,i)=>'<span class="chip" style="border-color:'+COLS[i%5]+'">● '+E(c.label)+'</span>').join(""))+(D.mode==="chronicle"?'<span class="chip">hover a person for their name · click to open their story</span><span class="chip">◎ known for harm</span>':'<span class="chip">● undecided</span><span class="chip">◎ committed</span><span class="chip">named citizens are labelled; dots move between places each hour; bubbles are what was said</span>');
function animateTo(h,ms){cancelAnimationFrame(anim.raf);const t0=performance.now();const step=(now)=>{const f=ms?Math.min(1,(now-t0)/ms):1;drawMap(h,f);if(f<1)anim.raf=requestAnimationFrame(step)};anim.raf=requestAnimationFrame(step)}
$("#expand").onclick=()=>{const s=$(".sticky");s.classList.toggle("open");const o=s.classList.contains("open");$("#expand").setAttribute("aria-pressed",String(o));$("#expand").textContent=o?"board ▴":"board ▾"};
document.querySelectorAll("[data-sph]").forEach(b=>b.onclick=()=>{sph=Number(b.dataset.sph);document.querySelectorAll("[data-sph]").forEach(x=>x.setAttribute("aria-pressed",String(x===b)));if(timer)start()});
try{const t=D.mode==="chronicle"?null:localStorage.getItem("ap-hour-"+location.pathname);if(t&&Number(t)>0&&Number(t)<D.hours){hour=Number(t);$("#resume").textContent="resumed at "+(D.tickLabels?D.tickLabels[hour-1]:"hour "+hour)+" — drag to 0 to start over"}}catch(e){}
setHour(hour);window.addEventListener("beforeunload",()=>{try{localStorage.setItem("ap-hour-"+location.pathname,String(hour))}catch(e){}});
</script>${scene3dScript()}</body></html>`;
}

export function renderGallery(runs: { dir: string; r: Record_ }[]): string {
  const roots = runs.filter((x) => !x.r.parent), byParent = new Map<string, typeof runs>();
  for (const x of runs.filter((x) => x.r.parent)) { const k = x.r.parent!.lineage?.[0] ?? x.r.parent!.runId; (byParent.get(k) ?? byParent.set(k, []).get(k)!).push(x); }
  const ordered = [...roots.sort((a, b) => a.r.title.localeCompare(b.r.title) || a.r.seed - b.r.seed).flatMap((x) => [x, ...(byParent.get(x.r.runId) ?? []).sort((a, b) => a.dir.localeCompare(b.dir))]), ...runs.filter((x) => x.r.parent && !roots.some((rt) => rt.r.runId === (x.r.parent!.lineage?.[0] ?? x.r.parent!.runId)))];
  const cut = (s: string, n: number) => s.length <= n ? s : s.slice(0, n).replace(/\s+\S*$/, "") + "…";
  const cards = ordered.map(({ dir, r }) => {
    const total = Object.values(r.outcome).reduce((a, b) => a + b, 0);
    const bars = r.ending.choices.map((c, i) => `<div class="bar"><span class="small">${esc(c.label)}</span><span><i style="width:${Math.round(((r.outcome[c.id] ?? 0) / total) * 100)}%;background:var(--acc${i ? i + 1 : ""})"></i></span><span class="small">${r.outcome[c.id] ?? 0}</span></div>`).join("");
    return `<a class="card${r.parent ? " fork" : ""}" href="${esc(dir)}/index.html" title="${esc(r.parent?.change ?? "")}"><b>${esc(r.title)}</b> <span class="mute">seed ${r.seed} · ${esc(r.brain)}${r.parent ? " · fork" : ""}</span><div class="small mute"><code>${esc(dir)}</code></div><div class="bars">${bars}</div><div class="small mute">${r.citizens.length} citizens · ${r.beats.filter((b) => b.level >= 2).length} beats${r.parent ? `<br>↳ ${esc(cut(r.parent.change, 110))}${r.parent.firstDivergence !== null ? ` · splits at h${r.parent.firstDivergence}` : ""}` : ""}</div></a>`;
  }).join("");
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Uncanny Valley — worlds</title><style>${CSS}</style></head><body><main><h1>Uncanny Valley</h1><p class="premise">Finite worlds. Every one ends; every one is on record.</p><div class="gallery grid2">${cards || "<p>No archives yet — run <code>pnpm world last-ferry --seed 7</code>.</p>"}</div></main></body></html>`;
}

/** Write index.html into one archive dir, or into every archive dir plus the gallery. */
export function buildSite(target?: string, root = "archive"): string[] {
  const dirs = target ? [existsSync(target) ? target : join(root, target)] : readdirSync(root).map((d) => join(root, d)).filter((d) => existsSync(join(d, "record.json")));
  const written: string[] = [];
  const runs: { dir: string; r: Record_ }[] = [];
  for (const d of dirs) {
    if (!existsSync(join(d, "record.json"))) throw new Error(`no record.json in ${d}`);
    const r = JSON.parse(readFileSync(join(d, "record.json"), "utf8")) as Record_;
    writeFileSync(join(d, "index.html"), renderWorldPage(r, { forkMd: existsSync(join(d, "fork.md")) ? "fork.md" : undefined }));
    written.push(join(d, "index.html")); runs.push({ dir: d.split("/").pop()!, r });
  }
  if (!target) { const all = readdirSync(root).map((d) => join(root, d)).filter((d) => existsSync(join(d, "record.json"))).map((d) => ({ dir: d.split("/").pop()!, r: JSON.parse(readFileSync(join(d, "record.json"), "utf8")) as Record_ })); writeFileSync(join(root, "index.html"), renderGallery(all)); written.push(join(root, "index.html")); }
  return written;
}
